apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa
  namespace: dvwa
spec:
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
        - name: dvwa
          image: vulnerables/web-dvwa
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_USER
              value: "dvwauser"
            - name: MYSQL_PASSWORD
              value: "dvwapassword"
            - name: MYSQL_DATABASE
              value: "dvwa"
          ports:
            - containerPort: 80
